/* 
   Description:  เพิ่มตารางสำหรับห้องบุคลากร เพื่อให้การีมได้ใช้เป็นข้อมูลพื้นฐาน
   Date: 04/04/2015
*/

CREATE TABLE IF NOT EXISTS `department` (
  `department_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ตาราง แผนก',
  `school_id` int(11) NULL COMMENT 'FK โรงเรียน',
  `name` varchar(64) NOT NULL COMMENT 'ชื่อ',
  `name_nd` varchar(64) DEFAULT NULL COMMENT 'ชื่อภาษาที่สอง',
  `created_by_id` int(11) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `modified_by_id` int(11) DEFAULT NULL,
  `modified_date` datetime DEFAULT NULL,
  PRIMARY KEY (`department_id`),
  KEY `fk_department_has_school_idx` (`school_id`),
  CONSTRAINT `fk_department_has_school` FOREIGN KEY (`school_id`) REFERENCES `school` (`school_id`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ตารางแผนก';

CREATE TABLE IF NOT EXISTS `job_position` (
  `job_position_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'ตาราง แผนก',
  `school_id` int(11) NULL COMMENT 'FK โรงเรียน',
  `name` varchar(64) NOT NULL COMMENT 'ชื่อ',
  `name_nd` varchar(64) DEFAULT NULL COMMENT 'ชื่อภาษาที่สอง',
  `created_by_id` int(11) DEFAULT NULL,
  `created_date` datetime DEFAULT NULL,
  `modified_by_id` int(11) DEFAULT NULL,
  `modified_date` datetime DEFAULT NULL,
  PRIMARY KEY (`job_position_id`),
  KEY `fk_job_position_has_school_idx` (`school_id`),
  CONSTRAINT `fk_job_position_has_school` FOREIGN KEY (`school_id`) REFERENCES `school` (`school_id`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ตารางแผนก';

CREATE TABLE IF NOT EXISTS `personal` (
  `personal_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'PK ตารางบุคลากร',
  `school_id` int(11) NOT NULL COMMENT 'FK โรงเรียน',
  `people_id` varchar(16) NOT NULL COMMENT 'หมายเลขบัตรประชาชน',
  `people_id_type` tinyint(4) NOT NULL COMMENT '*Fix ประเภทบัตรประชาชน',
  `prename` tinyint(4) NOT NULL COMMENT '*Fix ชื่อต้น',
  `firstname` varchar(64) NOT NULL DEFAULT '' COMMENT 'ชื่อ',
  `lastname` varchar(64) NOT NULL DEFAULT '' COMMENT 'นามสกุล',
  `firstname_nd` varchar(64) DEFAULT NULL COMMENT 'ชื่อภาษาที่สอง',
  `lastname_nd` varchar(64) DEFAULT NULL COMMENT 'สกุลภาษาที่สอง',
  `firstname_rd` varchar(64) DEFAULT NULL COMMENT 'ชื่อถาษาที่สาม',
  `lastname_rd` varchar(64) DEFAULT NULL COMMENT 'สกุลภาษาที่สาม',
  `nickname` varchar(32) DEFAULT NULL COMMENT 'ชื่อเล่น',
  `gender` tinyint(4) NOT NULL COMMENT '*Fix เพศ ',
  `religion` tinyint(4) NOT NULL COMMENT '*Fix ศาสนา',
  `race` smallint(6) NOT NULL COMMENT '*Fix เชื้อชาติ',
  `nationality` smallint(6) NOT NULL COMMENT '*Fix สัญชาติ',
  `marital_status` tinyint(4) NOT NULL COMMENT '*Fix สถานะการแต่งงาน',
  `birth_date` date NOT NULL COMMENT 'วันเดือนปี เกิด ',
  `blood` tinyint(4) NOT NULL COMMENT '*Fix หมู่เลือด',
  `height` float DEFAULT NULL COMMENT 'ส่วนสูง',
  `weight` float DEFAULT NULL COMMENT 'น้ำหนัก',
  `congenital_disease` varchar(256) DEFAULT NULL COMMENT 'โรคประจำตัว',
  `expert` varchar(256) DEFAULT NULL COMMENT 'ความเชียวชาญ',
  `capability` varchar(256) DEFAULT NULL COMMENT 'ความสามารถพืเศษ',
  `father_id` int(11) DEFAULT NULL COMMENT 'FK บิดา',
  `mother_id` int(11) DEFAULT NULL COMMENT 'FK มารดา',
  `created_by_id` int(11) DEFAULT NULL COMMENT 'FK ผู้ลงข้่อมูล',
  `created_date` datetime DEFAULT NULL COMMENT 'วันที่ลงข้อมูล',
  `modified_by_id` int(11) DEFAULT NULL COMMENT 'FK ผู้แก้ไขข้อมูล',
  `modified_date` datetime DEFAULT NULL COMMENT 'วันที่แก้ไขข้อมูล',
  PRIMARY KEY (`personal_id`),
  UNIQUE KEY `personal_columns_uniq` (`school_id`,`people_id`,`people_id_type`),
  KEY `fk_personal_has_mother` (`mother_id`),
  KEY `fk_personal_has_father` (`father_id`),
  KEY `fk_personal_has_school_idx` (`school_id`),
  CONSTRAINT `fk_personal_has_father` FOREIGN KEY (`father_id`) REFERENCES `family` (`family_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_personal_has_mother` FOREIGN KEY (`mother_id`) REFERENCES `family` (`family_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_personal_has_school` FOREIGN KEY (`school_id`) REFERENCES `school` (`school_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ข้อมูลพื้นฐานบุคลากร';

CREATE TABLE IF NOT EXISTS `personal_graduated_history` (
  `graduated_history_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'PK ตารางประวัติการศึกษา',
  `personal_id` int(11) NOT NULL COMMENT 'FK บุคลากร',
  `institute` varchar(128) NOT NULL COMMENT 'ชื่อสถาบัน',
  `graduated_level` tinyint(4) NOT NULL COMMENT '*Fix ระดับการศึกษาที่จบ',
  `degree` varchar(128) DEFAULT NULL COMMENT 'วุฒิการศึกษา',
  `major` varchar(128) DEFAULT NULL COMMENT 'วิชาเอก',
  `minor` varchar(128) DEFAULT NULL COMMENT 'วิชาโท',
  `description` varchar(256) DEFAULT NULL COMMENT 'วิชาโท',
  `year` int(11) DEFAULT NULL COMMENT 'ปีทืจบ',
  `location` varchar(128) DEFAULT NULL COMMENT 'สถานที่สถาบัน',
  `province_id` int(11) NOT NULL COMMENT 'จังหวัดสถาบัน',
  `created_by_id` int(11) DEFAULT NULL COMMENT 'FK ผู้ใส่ข้อมูล',
  `created_date` datetime DEFAULT NULL COMMENT 'วันที่ใส่ข้อมูล',
  `modified_by_id` int(11) DEFAULT NULL COMMENT 'FK ผู้แก้ไขข้อมูล',
  `modified_date` datetime DEFAULT NULL COMMENT 'วันที่แก้ไขข้อมูล',
  PRIMARY KEY (`graduated_history_id`),
  KEY `fk_graduated_history_has_personal_idx` (`personal_id`),
  CONSTRAINT `fk_graduated_history_has_personal` FOREIGN KEY (`personal_id`) REFERENCES `personal` (`personal_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ประวัติการศึกษาบุคลากร';

CREATE TABLE IF NOT EXISTS `personal_work` (
  `personal_work_id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'PK ตารางข้อมูลบุคลากรที่ทำงาน',
  `school_id` int(11) NOT NULL COMMENT 'FK โรงเรียน',
  `personal_id` int(11) NOT NULL COMMENT 'FK บุคลากร',
  `personal_status` tinyint(4) NOT NULL COMMENT '*Fix สถานะบุคลากร เช่น ลาออก ไล่ออก ทำงาน',
  `personal_code` varchar(16) NOT NULL DEFAULT '' COMMENT 'รหัสบุคลากร',
  `personal_image` varchar(512) DEFAULT NULL COMMENT 'รูปภาพ',
  `job_position_id` int(11) DEFAULT NULL COMMENT 'ตำแหน่ง',
  `department_id` int(11) DEFAULT NULL COMMENT 'แผนก',
  `salary` float NOT NULL COMMENT 'เงินเดือน',
  `tax` float NOT NULL COMMENT 'ภาษี',
  `other_revenue` float NOT NULL COMMENT 'เงินรายได้อื่น ๆ ',
  `extra_revenue` float NOT NULL COMMENT 'เงินสนับสนุนค่าครองชีพ',
  `tel` varchar(16) DEFAULT NULL COMMENT 'โทรศัพท์',
  `mobile` varchar(16) DEFAULT NULL COMMENT 'มือถือ',
  `email` varchar(64) DEFAULT NULL COMMENT 'อีเมลล์',
  `census_address` varchar(256) DEFAULT NULL COMMENT 'ที่อยู่ตามทะเบียนบ้าน',
  `census_city_id` int(11) DEFAULT NULL COMMENT 'ตำบล ที่อยู่ตามทะเบียนบ้าน',
  `census_district_id` int(11) DEFAULT NULL COMMENT 'อำเภอ ที่อยู่ตามทะเบียนบ้าน',
  `census_province_id` int(11) DEFAULT NULL COMMENT 'จังหวัด ที่อยู่ตามทะเบียนบ้าน',
  `census_postcode_id` int(11) DEFAULT NULL COMMENT 'ไปรษณีย์ ที่อยู่ตามทะเบียนบ้าน',
  `current_address` varchar(256) DEFAULT NULL COMMENT 'ที่อยู่ปัจจุบัน',
  `current_city_id` int(11) DEFAULT NULL COMMENT 'ตำบล ที่อยู่ปัจจุบัน',
  `current_district_id` int(11) DEFAULT NULL COMMENT 'อำเภอ ที่อยู่ปัจจุบัน',
  `current_province_id` int(11) DEFAULT NULL COMMENT 'จังหวัด ที่อยู่ปัจจุบัน',
  `current_postcode_id` int(11) DEFAULT NULL COMMENT 'ไปรษณีย์ ที่อยู่ปัจจุบัน',
  `employment_type` tinyint(4) NOT NULL COMMENT '*Fix ประเภทการว่าจ้าง',
  `start_work_date` date NOT NULL COMMENT 'วันที่เริ่มทำงาน',
  `recruit_by_id` int(11) NOT NULL COMMENT 'FK ผู้รับสมัคร',
  `recruit_date` date NOT NULL COMMENT 'วัน เดือน ปีที่รับสมัคร',
  `recruit_type` tinyint(4) NOT NULL COMMENT '*Fix ประเภทการสมัคร ',
  `recruit_description` varchar(256) DEFAULT NULL COMMENT 'รายละเอียดการสมัคร',
  `resign_by_id` int(11) DEFAULT NULL COMMENT 'FK ผู้รับเรื่องการลาออก',
  `resign_date` date DEFAULT NULL COMMENT 'วันเดือน ปี ปี ที่ลาออก',
  `resign_type` tinyint(4) DEFAULT NULL COMMENT '*Fix ประเภทการลาออก',
  `resign_description` varchar(256) DEFAULT NULL COMMENT 'รายละเอียดการลาออก',
  `bank_name` varchar(64) DEFAULT NULL COMMENT 'ชื่อธนาคาร',
  `bank_account_number` varchar(32) DEFAULT NULL COMMENT 'หมายเลขบัญชี',
  `bank_account_type` tinyint(4) DEFAULT NULL COMMENT '*Fix ประเภทบัญชี',
  `bank_account_name` varchar(32) DEFAULT NULL COMMENT 'ชื่อบัญชี',
  `bank_account_branch` varchar(128) DEFAULT NULL COMMENT 'สาขา',
  `bank_account_province_id` int(11) DEFAULT NULL COMMENT 'จังหวัด',
  `spouse_id` int(11) DEFAULT NULL COMMENT 'FK คู่สมรส',
  `created_by_id` int(11) DEFAULT NULL COMMENT 'FK ผู้ใส่ข้อมูล',
  `created_date` datetime DEFAULT NULL COMMENT 'วันที่ใส่ข้อมูล',
  `modified_by_id` int(11) DEFAULT NULL COMMENT 'FK ผู้แก้ไขข้อมูล',
  `modified_date` datetime DEFAULT NULL COMMENT 'วันที่แก้ไขข้อมูล',
  PRIMARY KEY (`personal_work_id`),
  UNIQUE KEY `personal_code_uni` (`school_id`,`personal_code`),
  KEY `fk_personal_work_has_personal_idx` (`personal_id`),
  KEY `fk_personal_work_has_spouse_idx` (`spouse_id`),
  KEY `fk_personal_work_has_department` (`department_id`),
  KEY `fk_personal_work_has_job_position` (`job_position_id`),
  KEY `fk_personal_work_has_school_idx` (`school_id`),
  CONSTRAINT `fk_personal_work_has_department` FOREIGN KEY (`department_id`) REFERENCES `department` (`department_id`),
  CONSTRAINT `fk_personal_work_has_job_position` FOREIGN KEY (`job_position_id`) REFERENCES `job_position` (`job_position_id`),
  CONSTRAINT `fk_personal_work_has_personal` FOREIGN KEY (`personal_id`) REFERENCES `personal` (`personal_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_personal_work_has_spouse` FOREIGN KEY (`spouse_id`) REFERENCES `family` (`family_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_personal_work_has_school` FOREIGN KEY (`school_id`) REFERENCES `school` (`school_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='ข้อมูลบุคลากร';
